name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: dhruvnub
          outputs: |
            dist/snake.svg?color_snake=%230891B2&color_dots=%23EBEDF0,%23BAE6FD,%2338BDF8,%230EA5E9,%230369A1
            dist/snake-dark.svg?color_snake=%2322D3EE&color_dots=%23161B22,%230E3A47,%23155E75,%230891B2,%2322D3EE

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
